### ISSUE TITLE
Implement fasttext java API to search through word vectors

### ISSUE THREAD

**Issue by plxCrush** [plxCrush/finalproject#18]

**Comment by plxCrush** [comment]
https://github.com/vinhkhuc/JFastText

**Comment by plxCrush** [comment]
https://github.com/facebookresearch/fastText/issues/52

**Comment by emregonen** [comment]
https://fasttext.cc/docs/en/unsupervised-tutorial.html

**Comment by emregonen** [comment]
https://stackoverflow.com/questions/4644415/java-how-to-get-input-from-system-console
